name: 'Update Reference Screenshots'
description: 'Update Reference Screenshots - Stubbed'

on:
  workflow_dispatch:

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - uses: actions/download-artifact@v2
      with:
        path: ./core/artifacts
    - name: Extract Archives
      run: |
        for file in *; do
          echo "$file"
        done
      shell: bash
      working-directory: ./core/artifacts
