language: node_js
node_js:
  - 0.10.26
env:
  - SNAPSHOT_BROWSER=chrome SNAPSHOT_BROWSER=safari
  - SNAPSHOT_BROWSER_ID=chrome_desktop_narrow SNAPSHOT_BROWSER_ID=safari_desktop_narrow
  - SNAPSHOT_WIDTH=400
  - SNAPSHOT_HEIGHT=800
branches:
  only:
    - master
before_install:
  - npm install -g protractor gulp
script:
  SNAPSHOT_TEST_ID=$(git rev-parse HEAD)

  gulp demos --demo-version=nightly
  protractor config/protractor.conf.js \
    --browser "$SNAPSHOT_BROWSER" \
    --params.platform_id="$SNAPSHOT_BROWSER_ID" \
    --params.width="$SNAPSHOT_WIDTH" \
    --params.height="$SNAPSHOT_HEIGHT" \
    --params.test_id="$SNAPSHOT_TEST_ID"
