language: node_js
node_js:
- 0.10

env:
  global:
    secure: C49JZxX08FSiXEZYpIFDs4YRdZGB0Hyygkk8zFknALLxPCREwk/MLhs64FOftgcVYjyo1CpmEZfmlKdHDnuko8mUjERrn/3iFHO2Fi0Z/zbj1pDkHlkoeIWGu3JS9y5mDAC1N0AO+pbMQp1jy+qTbHZsBsRCM4tVeEoLVdLmwOU=

before_install:
- gem update --system
- gem install sass
- npm install -g grunt-cli

before_script:
- export REMOTE=ajoslin
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start

script:
- ./scripts/travis/ci.sh
