name: 'Ionic Nightly Build'

on:
  workflow_dispatch:

  # TODO remove this before merging
  # This is so we can test in the PR
  pull_request:
    branches: [ '**' ]

jobs:
  nightly-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install Dependencies
        run: npm ci --no-package-lock && lerna bootstrap --ignore-scripts -- --legacy-peer-deps
        shell: bash
      - name: Prepare NPM Token
        run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
        shell: bash
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Configure Identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      # A 1 is required before the timestamp
      # as lerna will fail when there is a leading 0
      # See https://github.com/lerna/lerna/issues/2840
      - name: Create Nightly Hash
        # The date should output YYYYMMDD
        # so that it is human readable
        run: |
          echo "HASH=1$(git log -1 --format=%H | cut -c 1-7)" >> $GITHUB_ENV
          echo "DATE=1$(date +%Y%m%d)" >> $GITHUB_ENV
          echo "CURRENT_VERSION=$(node ./.scripts/bump-version.js)" >> $GITHUB_ENV
        shell: bash
      - name: Checkout Nightly Branch
        run: |
          git checkout -b nightly-$(echo "${{ env.DATE }}")-$(echo "${{ env.HASH }}")
          git push origin nightly-$(echo "${{ env.DATE }}")-$(echo "${{ env.HASH }}")
        shell: bash
      - name: Create Nightly Build
        run: |
          HUSKY_SKIP_HOOKS=1 lerna publish $(echo "${{ env.CURRENT_VERSION }}")-nightly.$(echo "${{ env.DATE }}").$(echo "${{ env.HASH }}") --no-verify-access --yes --force-publish='*' --dist-tag nightly --conventional-commits --conventional-prerelease --exact --create-release github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
      # We need to push the commit changes in order for the tags
      # to get updated, but we don't need to keep the changelog
      # changes around.
      - name: Delete Nightly Branch
        run: |
          git branch -d nightly-$(echo "${{ env.DATE }}")-$(echo "${{ env.HASH }}")
          git push origin --delete nightly-$(echo "${{ env.DATE }}")-$(echo "${{ env.HASH }}")
        shell: bash
