name: 'Ionic Framework Build (Stencil Nightly)'

on:
  schedule:
    - cron: "0 0 * * 1-5" # Run at midnight, Monday-Friday (inclusive)

jobs:
  build-core-stencil-nightly:
    runs-on: ubuntu-latest
    steps:
      - run: |
          git checkout -b stencil-nightly-tmp
      - uses: ./.github/workflows/actions/build-core-stencil-nightly

  test-core-clean-build:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-clean-build

  test-core-lint:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-lint

  test-core-spec:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-spec

  test-core-e2e:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-e2e

  test-core-screenshot:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main' && !github.event.pull_request.head.repo.fork
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-screenshot
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  test-core-screenshot-main:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/actions/test-core-screenshot-main
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  build-vue:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-vue

  build-vue-router:
    needs: [build-vue]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-vue-router

  test-vue-e2e:
    needs: [build-vue, build-vue-router]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-vue-e2e

  build-angular:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-angular

  build-angular-server:
    needs: [build-angular]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-angular-server

  test-angular-e2e:
    needs: [build-angular, build-angular-server]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-angular-e2e

  build-react:
    needs: [build-core-stencil-nightly]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-react

  build-react-router:
    needs: [build-react]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/build-react-router

  test-react-router-e2e:
    needs: [build-react, build-react-router]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-react-router-e2e

  test-react-e2e:
    needs: [build-react, build-react-router]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/actions/test-react-e2e
